baseURL = 'https://matsick.com/'
languageCode = 'en-us'
title = 'Caleb Matsick'
theme = 'archie'
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
mode="auto"
useCDN=false
subtitle = "Security Engineer by day, Software Engineer by night"
favicon="https://raw.githubusercontent.com/calebmatsick/matsick.com/master/favicon.ico"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/calebmatsick"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/CalebMatsick"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
